### ISSUE TITLE
Create Category:wrong error message when empty title

### ISSUE THREAD

**Issue by yanaaleeva** [viraxslot/online-school-app#13]
**Steps to reproduce**

Steps to reproduce
1. In Postman create collection, e.g. "Bug report"
2.  Click "Add request"
3. Name request, e.g. "admin login"
4.  Type in Body: 
{
    "username": "admin",
    "password": "************"
}
5. Create admin Token by typing in Tests: const body = pm.response.json()
 pm.environment.set('adminToken', body.accessToken)
6. Send POST request to http://qa-school-test.quantori.academy/api/v1/session
7. Click "Add request" 
8. Name request, e.g. "empty title"
9. Type into Body :
{
  "title": ""
}
10. Insert Bearer Token "adminToken" into Auth
11. Insert to Tests:
pm.test("Error text is correct", function () {
    const body = pm.response.json()
       pm.expect(body.errors[0].msg).to.equal("Only RU/EN alphabet, space and digits allowed, please change your request");
});
12. Send Post request to http://qa-school-test.quantori.academy/api/v1/categories

**Actual behavior**
Error message text states: "errors": "Only RU/EN alphabet and digits allowed, please change your request"
**Expected behavior**
Error message text should state:"errors": "Only RU/EN alphabet, space and digits allowed, please change your request"
**Screenshots**
![empty_error message](https://user-images.githubusercontent.com/105941331/174500077-8982e3de-2078-4972-b889-f6a0750a9680.jpg)

**Comment by LiliaUsol** [comment]
The same problem with course title and course description revealed. The user will be confused.

**Comment by viraxslot** [comment]
@LiliaUsol hi, it's better the create a separate bug for the "course" endpoint. But for the course title/description any character is allowed, so I don't see any problem. Do you want to add this rule?
