### ISSUE TITLE
Category title field is allowed to have spaces only

### ISSUE THREAD

**Issue by LarisaTerenteva** [viraxslot/online-school-app#17]
**Description**
It is possible to create category with title consisting of spaces only, allowing such names in categories list seems not to be user friendly, as such names wouldn't look nice in the list.

**Steps to reproduce**
1. Login to active user with admin role account
2. Save access token for admin to use it in following request
3. Input {"title": "name"}, where name is string of spaces of valid length (3-100) in POST request Body
4. Use saved admin access token for authorization
5. Make POST request to http://qa-school-test.quantori.academy/api/v1/categories

**Actual behavior**
1. Response code is 200 OK
2. No error message is shown
3. New category is created with title: "name", where name is string of spaces of valid length (3-100) 

**Expected behavior**
1. Code 400 Bad request
2. Error message is shown
3. Category is not created

**Screenshots**
![10 1](https://user-images.githubusercontent.com/106036717/174682261-92c3e1ce-bf5b-42a6-a760-29f078c5de91.PNG)
![10 2](https://user-images.githubusercontent.com/106036717/174682539-d7b7b2bf-0e95-433c-b3e9-237122f6abd0.PNG)

**Comment by viraxslot** [comment]
Fixed here: https://github.com/viraxslot/online-school-app/commit/142458a43ac3169526d42719b5172607e55197ec
Sorry, automatically pushed to the `dev` branch, already enabled the rule that disallow that.
