### ISSUE TITLE
Create/change course: impossible to use description of length 499 or 500

### ISSUE THREAD

**Issue by yanaaleeva** [viraxslot/online-school-app#21]
Pre-conditions 
There exists valid teacher role account with valid credentials
There exists category with "categoryId"=1
Steps to reproduce
In Postman create collection, e.g. "Bug report"
Click "Add request"
Name request, e.g. "teacher login"
Type in 'Body':

{
"username": "teacher",
"password": "************"
}

Create teacher Token by typing in 'Tests':
 const body = pm.response.json()
pm.environment.set('teacherToken', body.accessToken)

Send POST request to http://qa-school-test.quantori.academy/api/v1/session

Click "Add request"
Name request, e.g. "invalid course description"
Test case1 "499 char":
Type into Body :

{
“title”: “QA course 1",
“description”: "descriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptioriptiodescriptiodes",
“visible”: "true",
“categoryId”:  "1"
}
For test case2 "500 char length":
{
“title”: “QA course 1",
“description”: "descriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptioriptiodescriptiodess",
“visible”: "true",
“categoryId”:  "1"
}
Send Post request to http://qa-school-test.quantori.academy/api/v1/courses

Actual result:
Code 500
Error message text:""errors": "Unable to create course: SequelizeDatabaseError: value too long for type character varying(255)""

Expected result:
Code 200
User should be able to create course with description length below 500 characters.

Screenshot:
![image](https://user-images.githubusercontent.com/105941331/175001231-e4a9c1a5-f526-4bbd-b4a7-2349194d8ff0.png)

**Comment by plushkinaaa** [comment]
I've got another response with description length of 500 chars. And it's behavior is unpredictable because one time it response correct with 200 chars and the next time with the same length it answers incorrect.

![400](https://user-images.githubusercontent.com/106329316/175782117-66dd2325-cd5f-433c-a1d8-7d2eab3580a5.png)

**Comment by viraxslot** [comment]
@yanaaleeva please feel free to recheck.

**Comment by yanaaleeva** [comment]
@viraxslot got code 200 for all 4 requests
