### ISSUE TITLE
Change course: impossible to change description of length below max boundary (499 char) and at max boundary (500 char)

### ISSUE THREAD

**Issue by yanaaleeva** [viraxslot/online-school-app#22]
Pre-conditions
There exists valid teacher role account with valid credentials
There exists category with "categoryId"=1
There exists course with "id"=1 and title "zagolovok"
Steps to reproduce
In Postman create collection, e.g. "Bug report"
Click "Add request"
Name request, e.g. "teacher login"
Type in 'Body':

{
"username": "teacher",
"password": "************"
}

Create teacher Token by typing in 'Tests':
const body = pm.response.json()
pm.environment.set('teacherToken', body.accessToken)

Send POST request to http://qa-school-test.quantori.academy/api/v1/session

Click "Add request"
Name request, e.g. "invalid course description"
Test case1 "499 char":
Type into Body :

{
"id": "1",
"title": "zagolovok1",
"description": "descriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptioriptiodescriptiodes",
“visible”: "true",
“categoryId”: "1"
}
For test case2 "500 char length":
{
"id": "1",
"title": "zagolovok1",
"description": "descriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptiodescriptioriptiodescriptiodess",
“visible”: "true",
“categoryId”: "1"
}
Send Patch request to http://qa-school-test.quantori.academy/api/v1/courses

Actual result:
Code 500
Error message text:""errors": "Unable to create course: SequelizeDatabaseError: value too long for type character varying(255)""

Expected result:
Code 200
User should be able to change course with description length below 500 characters.

Screenshot:
![image](https://user-images.githubusercontent.com/105941331/175000949-6c2ecd44-ba67-4043-94bd-0ad9a2949e37.png)

**Comment by LiliaUsol** [comment]
Let me add. Both bugs related to description length may be fixed if the maximumparameter is changed to 255 in requirement, cause BVA gives adequate results with this value.

**Comment by viraxslot** [comment]
Duplicates https://github.com/viraxslot/online-school-app/issues/21
