### ISSUE TITLE
There is no any error message if we create category with extra field

### ISSUE THREAD

**Issue by PetrushaOlga** [viraxslot/online-school-app#25]
There is no any error message if we create category with extra field. Category is created but all extras just disappear. I think,  the user should know if some of the entered information is not saved

**Steps to reproduce**
1. Login as admin
2. Create category with extra information or fields
```
{
  "title": "string",
  "extra": "string"
}
```
3. Send request

**Actual behavior**
 New category is created,  extra fields and information disappear

**Expected behavior**
Error message

**Screenshots**
![image](https://user-images.githubusercontent.com/106110950/174883328-4f84c259-b7d0-4f50-a6e1-3909327d3a6f.png)

**Comment by yanaaleeva** [comment]
Hello, I get this in json response as actual result: 
![image](https://user-images.githubusercontent.com/105941331/175058582-2ae71160-6005-4d94-87fa-77693e7d405d.png)

**Comment by yanaaleeva** [comment]
Hello @PetrushaOlga,
I get this as actual response 
![image](https://user-images.githubusercontent.com/105941331/175058936-28aa6be4-1612-4cab-83fb-ab6fbbfd9145.png)

**Comment by PetrushaOlga** [comment]
@yanaaleeva  Try the same request, but with comma after "gmail"

**Comment by viraxslot** [comment]
@PetrushaOlga I'd say it's a totally normal situation that additional fields are just ignored. Won't be fixed.

@yanaaleeva well, for consistency it can be done, of course. But it's kinda trivial problem.
