### ISSUE TITLE
500 error when creating course as teacher

### ISSUE THREAD

**Issue by ekomarova2312** [viraxslot/online-school-app#34]
**Pre-conditions:**
There exists a teacher account with valid credentials

**Steps to reproduce:**
Login with teacher account
Use the received token for authentication
Send a request:
POST http://qa-school-test.quantori.academy/api/v1/courses  
{
  "title": "course1238",
  "description": "rec",
  "visible": true,
  "categoryId": 352
}

**Actual behavior:**
500 Internal Server Error
"Unable to create course: SequelizeValidationError: notNull Violation: course.createdBy cannot be null"

**Expected behavior:**
The course is created

**Comment by viraxslot** [comment]
Duplicates https://github.com/viraxslot/online-school-app/issues/33
