### ISSUE TITLE
Code 400 instead of 401 when NoAuth user tries to remove a course

### ISSUE THREAD

**Issue by LarisaTerenteva** [viraxslot/online-school-app#47]
Description:
When NoAuth user tries to remove a course created by user with teacher role, wrong response code and error message are shown.

Pre-conditions:
1. There is at least one active user with admin role;
2. There is at least one active user with teacher role

Steps to reproduce:
1. Login to active user with admin role account;
2. Save access token for admin;
3. Create a new category by POST request (http://qa-school-test.quantori.academy/api/v1/categories) using saved admin access token, input in request body  is:
{"title": "string"}, with 'title' being a string of valid length (3-100) and allowed characters (RU/EN alphabet, space, digits);
4. Save the newly created category id to use in following request;
5.  Login to active user with teacher role account;
6. Save access token for teacher;
7. Create a new course by POST request (http://qa-school-test.quantori.academy/api/v1/courses) using saved teacher access token, input in request body  is:
{"title": "string",
  "description": "string",
  "visible": true,
  "categoryId": 0},
with 'title' being string of valid length (3-100) and allowed characters (RU/EN alphabet, space, digits), 'description' being string of valid length (3-255 as implemented at the moment), 'visible' being boolean, 'categoryId' being the id of the category created on the step 3;
8. Save the newly created course id to use in following request;
9. Try making DELETE request (http://qa-school-test.quantori.academy/api/v1/courses/{courseId}), where courseId is id of the course created on step 7, using No Auth authorization type

Post-conditions:
1. Delete the course created on step 7 by DELETE request (http://qa-school-test.quantori.academy/api/v1/courses/{courseId}) using teacher access token
2. Delete the category created on step 3 by DELETE request (http://qa-school-test.quantori.academy/api/v1/courses/{categoryId}) using admin access token

Actual behavior:
1. Response code is 400 Bad request
2. Error message is shown: "error": "There is no such endpoint! Please check the requested URL or Method. API docs can be found at /api/v1/api-docs"

Expected behavior:
1. Code 401 Unauthorized
2. Error message is shown: "error": "Unauthorized"

**Screenshots**
![1](https://user-images.githubusercontent.com/106036717/175836320-555200c1-fec5-4ba4-8e03-75c188e55fa7.PNG)

**Comment by viraxslot** [comment]
@LarisaTerenteva "no such endpoint" error will appear if the URL doesn't match any existing endpoint. Could you please try to check the URL and method?

**Comment by LarisaTerenteva** [comment]
Oops, my bad, I missed that URL wasn't right, sorry! There's no bug in this case.

**Comment by LarisaTerenteva** [comment]
Is it ok that I closed this bug by myself, as the bug is not valid?
