### ISSUE TITLE
Teacher can successfully change a course with 'visible' field absent in request

### ISSUE THREAD

**Issue by LarisaTerenteva** [viraxslot/online-school-app#49]
Description:
When teacher user tries to change a course without 'visible' field in request, course is successfully changed with code 200 and no error message. 

Pre-conditions:
1. There is at least one active user with admin role;
2. There is at least one active user with teacher role;

Steps to reproduce:
1. Login to active user with admin role account;
2. Save access token for admin;
3. Create a new category by POST request (http://qa-school-test.quantori.academy/api/v1/categories) using saved admin access token, input in request body  is:
{"title": "string"}, with 'title' being a string of valid length (3-100) and allowed characters (RU/EN alphabet, space, digits);
4. Save the newly created category id to use in following request;
5.  Login to active user with teacher role account;
6. Save access token for teacher;
7. Create a new course by POST request (http://qa-school-test.quantori.academy/api/v1/courses) using saved teacher access token, input in request body  is:
{"title": "string",
  "description": "string",
  "visible": true,
  "categoryId": 0},
with 'title' being string of valid length (3-100) and allowed characters (RU/EN alphabet, space, digits), 'description' being string of valid length (3-255 as implemented at the moment), 'visible' being boolean, 'categoryId' being the id of the category created on the step 3;
8. Save the newly created course id to use in following request;
9. Try making PATCH request (http://qa-school-test.quantori.academy/api/v1/courses), using saved teacher access token, input in request body  is:
{ "id": 0,
  "title": "string",
  "description": "string",
  "categoryId": 0},
with 'id' being the id of the course created on the step 7, 'title' being string of valid length (3-100) and allowed characters (RU/EN alphabet, space, digits), 'description' being string of valid length (3-255 as implemented at the moment), 'categoryId' being the id of the category created on the step 3

Post-conditions:
1. Delete the course created on step 7 by DELETE request (http://qa-school-test.quantori.academy/api/v1/courses/{courseId}) using teacher access token;
2. Make sure, course is deleted;
3. Delete the category created on step 3 by DELETE request (http://qa-school-test.quantori.academy/api/v1/courses/{categoryId}) using admin access token;
4. Make sure, category is deleted

Actual behavior:
1. Response code is 200 Ok
2. No error message is shown
3. Course is successfully changed

Expected behavior:
1. Code 400 Bad request
2. Error message is shown: "errors": 
         [{ "msg": "Parameter should be boolean",
            "param": "visible",
            "location": "body"}]
3. No changes applied to the course

**Screenshots**
![3](https://user-images.githubusercontent.com/106036717/175837258-e98e755c-427b-45d0-944e-311abf8b4d60.PNG)

**Comment by viraxslot** [comment]
@LarisaTerenteva PATCH method allows us to change the record partially, it's totally OK to change only 1 field or just several. But there is a bug with validation rules here: https://github.com/viraxslot/online-school-app/issues/38 
I need to fix it.

**Comment by LarisaTerenteva** [comment]
The question is, when any other field is missing from request, there is code 400 and error messages shown, 'visible' field was the only one, that could be missing without consequences. Should it be that way?
