### ISSUE TITLE
Underlined "dislike" in Postman response

### ISSUE THREAD

**Issue by Olesya-minakova** [viraxslot/online-school-app#71]
**Description**
In case of removing like/dislike the postman response gives underlined 'dislike'. The 'dislike' has link to a new request 
**Steps to reproduce**
1. POST for excised curse like via using this request http://qa-school-test.quantori.academy/api/v1/courses/{courseID}/like/yes
2. Created new request with next URL: http://qa-school-test.quantori.academy/api/v1/courses/{courseID}/like/remove
3. POST new created request

**Actual behavior**
The request return next body:
```javascript
{
    "result": "You've removed your like/[dislike](http://qa-school-test.quantori.academy/dislike) from the course"
}
```
Where the 'dislike' is underlined and has URL
**Expected behavior**
The request body should be like that
```javascript
{
    "result": "You've removed your like/dislike from the course"
}
```

*without any underlines or links
**Screenshots**
![Postman_PgXoJicn7r](https://user-images.githubusercontent.com/106233741/176933329-ef1fdaa7-433e-4a01-9c54-bdc0f803fd49.png)

**Comment by viraxslot** [comment]
@Olesya-minakova it's Postman bug, you can see in the console that backend returns no link:

![image](https://user-images.githubusercontent.com/20737672/179123030-cb1639bf-df47-4e56-9393-d9f97e54dc85.png)
